kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: oms-pv
  annotations:
    description: oms-pv
provisioner: kubevirt.io.hostpath-provisioner
parameters:
  storagePool: local
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
