kind: PersistentVolume
apiVersion: v1
metadata:
  name: oms-pv
spec:
  capacity:
    storage: 30Gi
  csi:
    driver: oms-kubevirt-storage
    volumeHandle: oms-pv
    volumeAttributes:
      csi.storage.k8s.io/pv/name: oms-pv
      storagePool: local
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oms-kubevirt-storage
  volumeMode: Filesystem
