kind: PersistentVolume
apiVersion: v1
metadata:
  name: 'oms-pv'
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: oms-nfs-storage
  nfs:
    path: /home/admin/apps/omshare
    server: 9.30.87.106
    readOnly: false
