apiVersion: apps.oms.ibm.com/v1beta1
kind: OMServer
metadata:
  name: omsagentserver
spec:
  name: omsagentserver
  upgradeStrategy: RollingUpdate
  replicaCount: 1
  podLabels:
    role: agent
  profile: agentserverprofile
  agentServer:
    names: [ScheduleOrder]
