apiVersion: apps.oms.ibm.com/v1beta1
kind: OMServer
metadata:
  name: omsintegrationserver
spec:
  name: omsintegrationserver
  upgradeStrategy: RollingUpdate
  replicaCount: 1
  podLabels:
    role: integration
  profile: agentserverprofile
  property:
    customerOverrides: AgentProperties
    envVars: EnvironmentVariablesAgent
    jvmArgs: JVMArguments
  integration:
    names: [CreateOrderInt]
