apiVersion: apps.oms.ibm.com/v1beta1
kind: OrderHub
metadata:
  annotations: {}
  name: orderhub
  namespace: oms
spec:
  networkPolicy:
    podSelector:
      matchLabels:
        release: oms
        role: appserver
    policyTypes:
      - Ingress
  adminURL: "https://omsappserver-oms.minikube/smcfs"
  license:
    accept: true
  additionalMounts: {}
  orderHub:
    base:
      livenessCheckBeginAfterSeconds: 900
      livenessFailRestartAfterMinutes: 10
      replicaCount: 1
      terminationGracePeriodSeconds: 60
    extn:
      livenessCheckBeginAfterSeconds: 900
      livenessFailRestartAfterMinutes: 10
      replicaCount: 1
      terminationGracePeriodSeconds: 60
  affinityAndTolerations: []
  upgradeStrategy: RollingUpdate
  networking:
    ingress:
      host: minikube
      ssl:
        enabled: true  
  serviceAccount: default
  image:
    base:
      imageName: om-orderhub-base
      pullPolicy: IfNotPresent
      repository: "cp.icr.io/cp/ibm-oms-enterprise"
      tag: "10.0.2209.2-amd64"
    extn:
      imageName: om-orderhub-ext
      pullPolicy: IfNotPresent
      repository: "cp.icr.io/cp/ibm-oms-enterprise"
      tag: "10.0.2209.2-amd64"
    imagePullSecrets:
      - name: ibm-entitlement-key
